### ISSUE TITLE
documentation is unclear

### ISSUE THREAD

**Issue by unix14** [TutorialsAndroid/SEmojis#1]
hey!
im trying to install your library into my project,

your documentation does not explain how to create this emojis keyboard
as you can see in this photo
https://github.com/TutorialsAndroid/SEmojis/blob/master/art/mockup002.png

thanks

**Comment by TutorialsAndroid** [comment]
> hey!
> im trying to install your library into my project,
> 
> your documentation does not explain how to create this emojis keyboard
> as you can see in this photo
> https://github.com/TutorialsAndroid/SEmojis/blob/master/art/mockup002.png
> 
> thanks

Firstly, Thanks for choosing my library. I will update Readme file with proper documentation soon. You haveto  wait for just one day to update proper documentation.

**Comment by unix14** [comment]
Cool!! thanks for the fast response! :)

**Comment by unix14** [comment]
Also, when i use EmojiconEditText inside my xml, the editor stop to render the preview and it says:
![image](https://user-images.githubusercontent.com/19227232/70266528-52896480-17a5-11ea-927f-df060168f3f2.png)
`java.lang.NullPointerException
	at android.text.style.DynamicDrawableSpan.getSize(DynamicDrawableSpan.java:120)
	at android.text.MeasuredParagraph.applyReplacementRun(MeasuredParagraph.java:524)
	at android.text.MeasuredParagraph.applyMetricsAffectingSpan(MeasuredParagraph.java:618)
	at android.text.MeasuredParagraph.buildForStaticLayout(MeasuredParagraph.java:440)
	at android.text.PrecomputedText.createMeasuredParagraphs(PrecomputedText.java:351)
	at android.text.StaticLayout.generate(StaticLayout.java:668)
	at android.text.DynamicLayout.reflow(DynamicLayout.java:609)
	at android.text.DynamicLayout.generate(DynamicLayout.java:477)
	at android.text.DynamicLayout.<init>(DynamicLayout.java:396)
	at android.text.DynamicLayout.<init>(DynamicLayout.java:45)
	at android.text.DynamicLayout$Builder.build(DynamicLayout.java:278)
	at android.widget.TextView.makeSingleLayout(TextView.java:8329)
	at android.widget.TextView.makeNewLayout(TextView.java:8204)
	at android.widget.TextView.onMeasure(TextView.java:8586)
	at android.view.View.measure_Original(View.java:23169)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:23133)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure_Original(View.java:23169)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:23133)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.cardview.widget.CardView.onMeasure_Original(CardView.java:260)
	at androidx.cardview.widget.CardView.onMeasure(CardView.java)
	at android.view.View.measure_Original(View.java:23169)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:23133)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure_Original(View.java:23169)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:23133)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure_Original(View.java:23169)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:23133)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
	at android.view.View.measure_Original(View.java:23169)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:23133)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.measureView(RenderSessionImpl.java:600)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:339)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:394)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:200)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:572)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$5(RenderTask.java:698)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`
and this
![image](https://user-images.githubusercontent.com/19227232/70266566-68972500-17a5-11ea-9cfb-b1c55e2fffd0.png)

**Comment by TutorialsAndroid** [comment]
> Also, when i use EmojiconEditText inside my xml, the editor stop to render the preview and it says:
> ![image](https://user-images.githubusercontent.com/19227232/70266528-52896480-17a5-11ea-927f-df060168f3f2.png)
> `java.lang.NullPointerException at android.text.style.DynamicDrawableSpan.getSize(DynamicDrawableSpan.java:120) at android.text.MeasuredParagraph.applyReplacementRun(MeasuredParagraph.java:524) at android.text.MeasuredParagraph.applyMetricsAffectingSpan(MeasuredParagraph.java:618) at android.text.MeasuredParagraph.buildForStaticLayout(MeasuredParagraph.java:440) at android.text.PrecomputedText.createMeasuredParagraphs(PrecomputedText.java:351) at android.text.StaticLayout.generate(StaticLayout.java:668) at android.text.DynamicLayout.reflow(DynamicLayout.java:609) at android.text.DynamicLayout.generate(DynamicLayout.java:477) at android.text.DynamicLayout.<init>(DynamicLayout.java:396) at android.text.DynamicLayout.<init>(DynamicLayout.java:45) at android.text.DynamicLayout$Builder.build(DynamicLayout.java:278) at android.widget.TextView.makeSingleLayout(TextView.java:8329) at android.widget.TextView.makeNewLayout(TextView.java:8204) at android.widget.TextView.onMeasure(TextView.java:8586) at android.view.View.measure_Original(View.java:23169) at android.view.View_Delegate.measure(View_Delegate.java:80) at android.view.View.measure(View.java:23133) at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749) at android.widget.FrameLayout.onMeasure(FrameLayout.java:185) at android.view.View.measure_Original(View.java:23169) at android.view.View_Delegate.measure(View_Delegate.java:80) at android.view.View.measure(View.java:23133) at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749) at android.widget.FrameLayout.onMeasure(FrameLayout.java:185) at androidx.cardview.widget.CardView.onMeasure_Original(CardView.java:260) at androidx.cardview.widget.CardView.onMeasure(CardView.java) at android.view.View.measure_Original(View.java:23169) at android.view.View_Delegate.measure(View_Delegate.java:80) at android.view.View.measure(View.java:23133) at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749) at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535) at android.widget.LinearLayout.measureVertical(LinearLayout.java:825) at android.widget.LinearLayout.onMeasure(LinearLayout.java:704) at android.view.View.measure_Original(View.java:23169) at android.view.View_Delegate.measure(View_Delegate.java:80) at android.view.View.measure(View.java:23133) at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749) at android.widget.FrameLayout.onMeasure(FrameLayout.java:185) at android.view.View.measure_Original(View.java:23169) at android.view.View_Delegate.measure(View_Delegate.java:80) at android.view.View.measure(View.java:23133) at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715) at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461) at android.view.View.measure_Original(View.java:23169) at android.view.View_Delegate.measure(View_Delegate.java:80) at android.view.View.measure(View.java:23133) at com.android.layoutlib.bridge.impl.RenderSessionImpl.measureView(RenderSessionImpl.java:600) at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:339) at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:394) at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:200) at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:572) at com.android.tools.idea.rendering.RenderTask.lambda$inflate$5(RenderTask.java:698) at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) `
> and this
> ![image](https://user-images.githubusercontent.com/19227232/70266566-68972500-17a5-11ea-9cfb-b1c55e2fffd0.png)

i tested this library on a fresh project it was working fine and views where showing correctly i think you should perform clean project and then rebuild the project i think it will work

**Comment by TutorialsAndroid** [comment]
> hey!
> im trying to install your library into my project,
> 
> your documentation does not explain how to create this emojis keyboard
> as you can see in this photo
> https://github.com/TutorialsAndroid/SEmojis/blob/master/art/mockup002.png
> 
> thanks

For sample click below how  i used this library in app see this.
[Emojicon](https://github.com/TutorialsAndroid/SEmojis/blob/master/app/src/main/java/semoji/developer/MainActivity.java)

**Comment by unix14** [comment]
Cool! looks nice, thanks!
